name: OldoeServer
version: 1.0.0
main: com.oldoe.plugin.Oldoe
description: Oldoe server plugin.
author: littlefryingpan
website: https://www.oldoe.com
api-version: 1.19
commands:
  spawn:
    description: "Go to spawn location"
    usage: "/spawn"
    aliases: [s, spawn]
  sethome:
    description: "Set home location"
    usage: "/sethome"
    aliases: [ sethome ]
  home:
    description: "Go to home location"
    usage: "/home"
    aliases: [ h, home ]
  plot:
    description: "Check status of plot"
    usage: "/plot"
    aliases: [ p, plot ]
  cash:
    description: "Check your cash balance"
    usage: "/cash"
    aliases: [ c, cash ]
  msg:
    description: "Send another user a private message"
    usage: "/msg"
    aliases: [ m, r, msg, message ]
  border:
    description: "Display plot borders"
    usage: "/border"
    aliases: [ border ]
  help:
    description: "Display command help"
    usage: "/help"
    aliases: [ h, help ]
  pvp:
    description: "Enable PVP"
    usage: "/pvp"
    aliases: [ pvp ]
  staff:
    description: "Staff command"
    usage: "/staff"
    aliases: [ s, staff ]
